# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhi-metrics", "prometheus" ]
    endpoint:
        health:
            show-details: when-authorized
        jhi-metrics:
            enabled: true
    info:
        git:
            mode: full
    health:
        mail:
            enabled: true # When using the MailService, configure an SMTP server and set this to true
    metrics:
        export:
            # Prometheus is the default metrics backend
            prometheus:
                enabled: true
                step: 60
        binders:
            jvm:
                enabled: true
            processor:
                enabled: true
            uptime:
                enabled: true
            logback:
                enabled: true
            files:
                enabled: true
            integration:
                enabled: true
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
        web:
            server:
                auto-time-requests: true

spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
    application:
        name: netflixdb
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev,test,prod,swagger"
    registration-closed: false

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: admin@netflixdb.pl
    swagger:
        default-include-pattern: /api/.*
        title: netflixdb API
        description: netflixdb API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
    sendgrid:
        api-key: "***REMOVED***"
    alias-by-title: "\
        Seven=Se7en,\"
        Treehouse Detectives=SKIP"
    przelewy24:
        merchant-id: "***REMOVED***"
    omdb-sync:
        api-key: "***REMOVED***"
        force-query-search: true
    fweb-sync:
        force-query-search: true
    netflix-sync:
        session-cookie: "***REMOVED***"
        shakti-url: "https://www.netflix.com/nq/website/memberapi/v1b6f8cb8/pathEvaluator?isVolatileBillboardsEnabled=true&routeAPIRequestsThroughFTL=false&isTop10Supported=true&falcor_server=0.1.0&withSize=true&materialize=true&original_path=/shakti/v1b6f8cb8/pathEvaluator"
        request-sleep-millis: 2000
        request-block-size: 48
        film-genre-by-id: "\
            1365=Action & Adventure Movies,\
            3063=Anime,\
            89844=Award winning Movies,\
            783=Children & Family Movies,\
            31574=Classic Movies,\
            6548=Comedies,\
            5824=Crime,\
            2243108=Documentaries,\
            5763=Dramas,\
            71590=Historical Movies,\
            8711=Horror Movies,\
            7077=Independent Movies,\
            52852=Music & Musicals,\
            6299=Polish Movies,\
            8883=Romantic Movies,\
            1492=Sci-Fi & Fantasy,\
            4370=Sport Movies,\
            11559=Stand-up Comedy,\
            2777752=Summer of Love,\
            8933=Thrillers"
        show-genre-by-id: "\
            10673=TV Action & Adventure,\
            6721=Anime TV,\
            78103=Asian TV Shows,\
            52117=British TV Shows,\
            10375=TV Comedies,\
            26146=Crime TV Shows,\
            10105=Docuseries,\
            11714=TV Dramas,\
            83181=Historical TV Shows,\
            81268388=History Documentaries,\
            52780=Science & Nature TV,\
            83059=TV Horror,\
            27346=Kids TV,\
            4366=TV Mysteries,\
            1622170=Polish TV Shows,\
            2070390=Reality Variety & Talk Shows,\
            26156=Romantic TV Shows,\
            1372=TV Sci-Fi & Fantasy,\
            60951=Teen TV Shows,\
            89811=TV Thrillers,\
            72404=US TV Shows"
