# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: INFO
        io.github.jhipster: INFO
        pl.kogx.netflixdb: INFO

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/netflixdb;DB_CLOSE_DELAY=-1
        username: netflixdb
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: 35.204.141.113:9300
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data
    liquibase:
        contexts: dev
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias netflixdb -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: netflixdb
# ===================================================================
server:
    port: 8080

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: netflixdb@localhost
        base-url: http://127.0.0.1:8080
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
    omdb-sync:
        api-key: "b9323085"
        force-query-search: true
    fweb-sync:
        force-query-search: true
    netflix-sync:
        session-cookie: "clSharedContext=46fa5082-e244-4843-a602-acccf748c050; memclid=a0c72348-32ff-4c22-b162-8be8bfa8544b; didUserInteractWithPage=true; hasSeenCookieDisclosure=true; dsca=customer; netflix-sans-normal-2-loaded=true; nfvdid=BQFmAAEBEN8bKTyPhC9ahD%2Bq8ytvR3Vgz5e%2FsZ8XDEdAnqw9882maazXxeBU43IvqZ1K5FKGbyByw3EJReuGuo1ffwIXcn5pGkWnD%2F9LfGbPnDz1KvX8naS4iD5Ra8J3fseISfTHOMAqiOhFxwc1aQwsTgx%2Bjbsf; SecureNetflixId=v%3D2%26mac%3DAQEAEQABABT2lW9sn3aYkvT4mznA8SJbFJUBeowa9dE.%26dt%3D1531552268843; NetflixId=v%3D2%26ct%3DBQAOAAEBEBNnQL5i6TGFiu9nHCXGxz2B0FcIVCnlx5_IRyD2O_Blph3jp3rQB-Bqo_gyoJxQczfBQ10s7co4DjezT6nbmekH_1BrnWK7JmejuTc2OCej81w6W242IF9JCI7fs44fZe6H_X4kweMcAQUnMZu3E9WjX5QVj-qgSQDy-KosFGMF4GujSjqsEbrrKVihxZ8WEl4_kHuBuc3CBrmMZmy5CtwFPYDX_p2l8FQTsvsRZ0hE_zBik-PrXf5yW-4s_6VM8QHEwv_SglCko7mZSO2LYiXKB0r2A-KB4roYNlFxDIpK5kXI42UltAShDlOY5ffhuFeruwSqej41zVqSt7mtqbACO2DhO3XImAbjBaMRlk3GvO_R0zbM7y2OOfH8OqXROrx0iMXwL-7sfOL1sx4g7H4_M3SIuM0PaihoKsptdINabCMG47pFfU-APawNUyOTTSdrtymH80krJ_F_7oVryCYh3S4K26plPAZoPpzAP6krh4ixcJMBUnDnX5-AAJ6ABAWc_-YndCIG9x8p51mBjF2D1MGrHR48Hd3HDcY2eRXNdXTEv1gd8AzfCPKI-oBWstdTDL89MJasyWk_d4G9A1d1-8sw4kzu1Y3dWB0nyx4VVQGiJnLMS7iA3E-Tvr8QZgLc%26bt%3Ddbl%26ch%3DAQEAEAABABSg1EhIJS7kIOX1MEXVK6b25p8_w8dgoOU.%26mac%3DAQEAEAABABTxWTA2dvEsrzv2W7feYBi9gE07Vv-A0HU.; profilesNewSession=0; lhpuuidh-browse-74Z72JFGLFD2HO4TSM3Q3WAJNE=PL%3APL-PL%3A25a33dcb-8ac8-41ce-9dd2-91b0af4452ce_ROOT; lhpuuidh-browse-74Z72JFGLFD2HO4TSM3Q3WAJNE-T=1531552269837; cL=1531552268984%7C153155218914081313%7C15315521896221154%7C%7C5%7CH7DNJNJATVANPPAHTA7AWQJ7OU; netflix-sans-bold-2-loaded=true"
        shakti-url: "https://www.netflix.com/api/shakti/d7cab521/pathEvaluator?isWatchlistEnabled=false&isShortformEnabled=false&isVolatileBillboardsEnabled=false&falcor_server=0.1.0&withSize=true&materialize=true"
        request-sleep-millis: 2000
        request-block-size: 48
        genre-by-id: "\
            1365=Action & Adventure Movies,\
            3063=Anime,\
            89844=Award winning Movies,\
            783=Children & Family Movies,\
            31574=Classic Movies,\
            6548=Comedies,\
            5824=Crime,\
            2243108=Documentaries,\
            5763=Dramas,\
            71590=Historical Movies,\
            8711=Horror Movies,\
            7077=Independent Movies,\
            52852=Music & Musicals,\
            6299=Polish Movies,\
            8883=Romantic Movies,\
            1492=Sci-Fi & Fantasy,\
            4370=Sport Movies,\
            11559=Stand-up Comedy,\
            2777752=Summer of Love,\
            8933=Thrillers,\
            10673=TV Action & Adventure,\
            6721=Anime TV,\
            78103=Asian TV Shows,\
            52117=British TV Shows,\
            10375=TV Comedies,\
            26146=Crime TV Shows,\
            10105=Docuseries,\
            11714=TV Dramas,\
            83181=Historical TV Shows,\
            83059=TV Horror,\
            27346=Kids TV,\
            4366=TV Mysteries,\
            1622170=Polish TV Shows,\
            2070390=Reality Variety & Talk Shows,\
            26156=Romantic TV Shows,\
            1372=TV Sci-Fi & Fantasy,\
            60951=Teen TV Shows,\
            89811=TV Thrillers,\
            72404=US TV Shows"
