# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump"]
    endpoint:
        health:
            show-details: when_authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: true # When using the MailService, configure an SMTP server and set this to true
    metrics:
        enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead

spring:
    application:
        name: netflixdb
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev,test,prod,swagger"
    registration-closed: false

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: admin@netflixdb.pl
    swagger:
        default-include-pattern: /api/.*
        title: netflixdb API
        description: netflixdb API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
    alias-by-title: "\
        Seven=Se7en,\"
        Treehouse Detectives=SKIP"
    przelewy24:
        merchant-id: "***REMOVED***"
    omdb-sync:
        api-key: "***REMOVED***"
        force-query-search: true
    fweb-sync:
        force-query-search: true
    netflix-sync:
        session-cookie: "memclid=a0c72348-32ff-4c22-b162-8be8bfa8544b; didUserInteractWithPage=true; hasSeenCookieDisclosure=true; dsca=customer; netflix-sans-normal-2-loaded=true; nfvdid=BQFmAAEBEN8bKTyPhC9ahD%2Bq8ytvR3Vgz5e%2FsZ8XDEdAnqw9882maazXxeBU43IvqZ1K5FKGbyByw3EJReuGuo1ffwIXcn5pGkWnD%2F9LfGbPnDz1KvX8naS4iD5Ra8J3fseISfTHOMAqiOhFxwc1aQwsTgx%2Bjbsf; netflix-sans-bold-2-loaded=true; _ga=GA1.2.1057021227.1531852465; VisitorId=002~a0c72348-32ff-4c22-b162-8be8bfa8544b~1531852465110~true~1531852465411~; clSharedContext=9560e2ce-9cf8-421e-96e4-8cfed309c98d; SecureNetflixId=v%3D2%26mac%3DAQEAEQABABQzLzmLr4rtiwLPwNW2FgkW-igx5JxqLMQ.%26dt%3D1536785427940; NetflixId=ct%3DBQAOAAEBEAeT3CKWTtNsZfkIRXMKQveCYLAoJ8frdA8OWuMSYh39SmUpTEGwDnQiVpORtB75HRm5YLFqUuNUr1MH6cyEUUk19dmpfbRJs_x7frVVl1F-BJBXJclpFmzunlhIqPnowqIYQm714vf4W_GgCLZfR5oj2rwyFY5rGafdpM_XH4K0Su10ezrvDyT0Z9P_RK0ioDCcBjfQAepMb_ThAzcyqYYFOGG6DRCFB1lxt4LIGXE8nGAWnc21l9AmmyZBLMBStzjZ9nJSBBsJwVVYmiyVC1sj95RYtFY67D7Z5MuThUkHP5FyoZENe0nCW3gJeSDTfgOuUfOZYS6cQQzM_2nHnu5YAGmiX8-Pcpe3R9R2jClLvNJUdQpVn22-XZs02XD-KHDMCLlvXlcRDrWrp_RGFoMEd8AoLqqPBR4Eu44DtDYvJmxdJN-_Zjy25WfP3yB-8H2loGHWiKmfU3_qQTTRJrEF6TJXsc2NYquUPiP9R31D_O16gA0geYTj0E9fJRJ6OHgz7IoRp70oX7y3QqLrRQZsr0zO77BtiTKuRTxL2c3RiAwXr4mHJqLjdDVoKiMHUdJyuGUv36tKNlIiC-5waArmsRFp3fDWWyuefvQM-MnFZFA107maQV4huMMxNdTwACxRMRY8Vz0_jTMYSOjWKJuN0EcJRE4BsisVnRz9VNisC8CbBzIW9PMM_vTILxoR3J9upu5M5F5KxfAtET3iG31l5RcgZVdVJBg_zCP4DVxp7MAF-XAh4K6-hbC2Qd5klMPGOla3FnKpRQ3T1an4hs9PbDMyZu47h-nwSBKtqelDKd7cq7VIaSCNNEkfkYKnQNvw%26bt%3Ddbl%26ch%3DAQEAEAABABSg1EhIJS7kIOX1MEXVK6b25p8_w8dgoOU.%26v%3D2%26mac%3DAQEAEAABABTWNTpis-MWsyOsZeTtZa8sOvros8Admjk.; profilesNewSession=0; lhpuuidh-browse-74Z72JFGLFD2HO4TSM3Q3WAJNE=PL%3AEN-PL%3Ab3b02c9c-41d8-49a0-b3dc-c83d2226ec82_ROOT; lhpuuidh-browse-74Z72JFGLFD2HO4TSM3Q3WAJNE-T=1536785438097"
        shakti-url: "https://www.netflix.com/api/shakti/v83012c76/pathEvaluator?isWatchlistEnabled=false&isShortformEnabled=false&isVolatileBillboardsEnabled=false&falcor_server=0.1.0&withSize=true&materialize=true"
        request-sleep-millis: 2000
        request-block-size: 48
        film-genre-by-id: "\
            1365=Action & Adventure Movies,\
            3063=Anime,\
            89844=Award winning Movies,\
            783=Children & Family Movies,\
            31574=Classic Movies,\
            6548=Comedies,\
            5824=Crime,\
            2243108=Documentaries,\
            5763=Dramas,\
            71590=Historical Movies,\
            8711=Horror Movies,\
            7077=Independent Movies,\
            52852=Music & Musicals,\
            6299=Polish Movies,\
            8883=Romantic Movies,\
            1492=Sci-Fi & Fantasy,\
            4370=Sport Movies,\
            11559=Stand-up Comedy,\
            2777752=Summer of Love,\
            8933=Thrillers"
        show-genre-by-id: "\
            10673=TV Action & Adventure,\
            6721=Anime TV,\
            78103=Asian TV Shows,\
            52117=British TV Shows,\
            10375=TV Comedies,\
            26146=Crime TV Shows,\
            10105=Docuseries,\
            11714=TV Dramas,\
            83181=Historical TV Shows,\
            83059=TV Horror,\
            27346=Kids TV,\
            4366=TV Mysteries,\
            1622170=Polish TV Shows,\
            2070390=Reality Variety & Talk Shows,\
            26156=Romantic TV Shows,\
            1372=TV Sci-Fi & Fantasy,\
            60951=Teen TV Shows,\
            89811=TV Thrillers,\
            72404=US TV Shows"
