version: '2'
services:
    netflixdb-app:
        image: netflixdb
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://netflixdb-mysql:3306/netflixdb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://netflixdb-elasticsearch:9200
        ports:
            - 8080:8080
    netflixdb-mysql:
        extends:
            file: mysql.yml
            service: netflixdb-mysql
    netflixdb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: netflixdb-elasticsearch
