version: '2'
services:
    netflixdb-elasticsearch:
        image: elasticsearch:5.6.5
        mem_limit: 1g
        # volumes:
        #     - ~/volumes/jhipster/netflixdb/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - ES_JAVA_OPTS=-Xms128m -Xmx512m # set to 50% of mem_limit, but no more than 31g
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
